require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'test/**'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 16
  
RSpec/ExampleLength:
  Max: 32

RSpec/ExpectInHook:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/Documentation:
  Enabled: false
