require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'config/**/*'
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

RSpec/MultipleExpectations:
  Max: 32