dist: trusty
language: ruby
rvm:
  - 2.5.3
services:
  - postgresql
before_script:
  - psql -c 'create database violet_test;' -U postgres
addons:
  postgresql: "10.5"
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec
